# frozen_string_literal: true

source "https://rubygems.org"

ruby "3.3.1"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.3", ">= 7.1.3.3"

# Use mysql as the database for Active Record
gem "mysql2", "~> 0.5"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[windows jruby]

# railsの起動時間を短縮する（標準gem）
gem "bootsnap", require: false

# 環境毎の設定管理を行う
gem "config"

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin Ajax possible
gem "rack-cors"

# 管理画面を簡単に作成する
gem "rails_admin", "~> 3.1.2"
gem "rails_admin-i18n"
gem "sassc-rails"
# Ruby3.4.0以降でcsvが標準ライブラリから削除されるため、gemで追加する
gem "csv"

# ユーザー認証を提供する
gem "devise"
# devise を日本語化する
gem "devise-i18n"
# ユーザーのトークン認証を提供する
gem "devise_token_auth"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "omniauth-rails_csrf_protection"
# '.env'を使う場合は以下も追加
gem "dotenv-rails"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[mri windows]
  # 開発環境でメール送信をテストする
  gem "letter_opener_web"
  # pry コンソールを使えるようにする。
  gem "pry-byebug"
  gem "pry-doc"
  gem "pry-rails"
  # テストフレームワーク rspec を導入する
  gem "rspec-rails"
  # rubocop を使えるようにする。
  gem "rubocop-faker"
  gem "rubocop-rails"
  gem "rubocop-rspec"
end

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end
